apiVersion: v1
kind: PersistentVolume
metadata:
  name: polardb-pv-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /opt/polardb-nfs/
    server: 10.77.50.218
    readOnly: false
