apiVersion: apps/v1
kind: Deployment
metadata:
  name: shardingsphere
  namespace: polardb
spec:
  replicas: 10
  selector:
    matchLabels:
      app: shardingsphere
  template:
    metadata:
      labels:
        app: shardingsphere
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: shardingsphere
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: shardingsphere
      containers:
      - name: shardingsphere
        image: apache/shardingsphere-proxy:5.2.0
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "/opt/shardingsphere-proxy/bin/start.sh " ]
        # command: ["tail"]
        # args: ["-f","/etc/os-release"]
        # env:
        # - name: PORT
        #   value: 3307
        ports:
        - containerPort: 3307
          name: polardb
          protocol: TCP
        volumeMounts: 
        - name: volume-shardingsphere-conf
          mountPath: /opt/shardingsphere-proxy/conf
          readOnly: true
        #resources:
          #limits:
            #cpu: "2000m"
            #memory: "2000Mi"
          #requests:
            #cpu: "800m"
            #memory: "1400Mi"
      volumes:
      - name: volume-shardingsphere-conf
        configMap:
          name: configmap-shardingsphere
